version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pipoca123
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init.sql