--changeset elise:03042024220958_populating_books_table
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Fundamentals of Wavelets','Goswami, Jaideva','signal_processing',228,'Wiley');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Data Smart','Foreman, John','data_science',235,'Wiley');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'God Created the Integers','Hawking, Stephen','mathematics',197,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Superfreakonomics','Dubner, Stephen','economics',179,'HarperCollins');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Orientalism','Said, Edward','history',197,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Nature of Statistical Learning Theory, The','Vapnik, Vladimir','data_science',230,'Springer');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Integration of the Indian States','Menon, V P','history',217,'Orient Blackswan');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Drunkard''s Walk, The','Mlodinow, Leonard','science',197,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Image Processing & Mathematical Morphology','Shih, Frank','signal_processing',241,'CRC');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'How to Think Like Sherlock Holmes','Konnikova, Maria','psychology',240,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Data Scientists at Work','Sebastian Gutierrez','data_science',230,'Apress');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Slaughterhouse Five','Vonnegut, Kurt','fiction',198,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Birth of a Theorem','Villani, Cedric','mathematics',234,'Bodley Head');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Structure & Interpretation of Computer Programs','Sussman, Gerald','computer_science',240,'MIT Press');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Age of Wrath, The','Eraly, Abraham','history',238,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Trial, The','Kafka, Frank','fiction',198,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Statistical Decision Theory''','Pratt, John','data_science',236,'MIT Press');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Data Mining Handbook','Nisbet, Robert','data_science',242,'Apress');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'New Machiavelli, The','Wells, H. G.','fiction',180,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Physics & Philosophy','Heisenberg, Werner','science',197,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Making Software','Oram, Andy','computer_science',232,'O''Reilly');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Analysis, Vol I','Tao, Terence','mathematics',248,'HBA');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Machine Learning for Hackers','Conway, Drew','data_science',233,'O''Reilly');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Signal and the Noise, The','Silver, Nate','data_science',233,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Python for Data Analysis','McKinney, Wes','data_science',233,'O''Reilly');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Introduction to Algorithms','Cormen, Thomas','computer_science',234,'MIT Press');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Beautiful and the Damned, The','Deb, Siddhartha','nonfiction',198,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Outsider, The','Camus, Albert','fiction',198,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Complete Sherlock Holmes, The - Vol I','Doyle, Arthur Conan','fiction',176,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Complete Sherlock Holmes, The - Vol II','Doyle, Arthur Conan','fiction',176,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Wealth of Nations, The','Smith, Adam','economics',175,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Pillars of the Earth, The','Follett, Ken','fiction',176,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Mein Kampf','Hitler, Adolf','nonfiction',212,'Rupa');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Tao of Physics, The','Capra, Fritjof','science',179,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Surely You''re Joking Mr Feynman','Feynman, Richard','science',198,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Farewell to Arms, A','Hemingway, Ernest','fiction',179,'Rupa');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Veteran, The','Forsyth, Frederick','fiction',177,'Transworld');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'False Impressions','Archer, Jeffery','fiction',177,'Pan');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Last Lecture, The','Pausch, Randy','nonfiction',197,'Hyperion');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Return of the Primitive','Rand, Ayn','philosophy',202,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Jurassic Park','Crichton, Michael','fiction',174,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Russian Journal, A','Steinbeck, John','nonfiction',196,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Tales of Mystery and Imagination','Poe, Edgar Allen','fiction',172,'HarperCollins');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Freakonomics','Dubner, Stephen','economics',197,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Hidden Connections, The','Capra, Fritjof','science',197,'HarperCollins');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Story of Philosophy, The','Durant, Will','philosophy',170,'Pocket');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Asami Asami','Deshpande, P L','fiction',205,'Mauj');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Journal of a Novel','Steinbeck, John','fiction',196,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Once There Was a War','Steinbeck, John','nonfiction',196,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Moon is Down, The','Steinbeck, John','fiction',196,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Brethren, The','Grisham, John','fiction',174,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'In a Free State','Naipaul, V. S.','fiction',196,'Rupa');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Catch 22','Heller, Joseph','fiction',178,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Complete Mastermind, The','BBC','nonfiction',178,'BBC');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Dylan on Dylan','Dylan, Bob','nonfiction',197,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Soft Computing & Intelligent Systems','Gupta, Madan','data_science',242,'Elsevier');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Textbook of Economic Theory','Stonier, Alfred','economics',242,'Pearson');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Econometric Analysis','Greene, W. H.','economics',242,'Pearson');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Learning OpenCV','Bradsky, Gary','data_science',232,'O''Reilly');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Data Structures Using C & C++','Tanenbaum, Andrew','computer_science',235,'Prentice Hall');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Computer Vision, A Modern Approach','Forsyth, David','data_science',255,'Pearson');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Principles of Communication Systems','Taub, Schilling','computer_science',240,'TMH');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Let Us C','Kanetkar, Yashwant','computer_science',213,'Prentice Hall');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Amulet of Samarkand, The','Stroud, Jonathan','fiction',179,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Crime and Punishment','Dostoevsky, Fyodor','fiction',180,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Angels & Demons','Brown, Dan','fiction',178,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Argumentative Indian, The','Sen, Amartya','nonfiction',209,'Picador');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Sea of Poppies','Ghosh, Amitav','fiction',197,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Idea of Justice, The','Sen, Amartya','nonfiction',212,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Raisin in the Sun, A','Hansberry, Lorraine','fiction',175,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'All the President''s Men','Woodward, Bob','history',177,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Prisoner of Birth, A','Archer, Jeffery','fiction',176,'Pan');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Scoop!','Nayar, Kuldip','history',216,'HarperCollins');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Ahe Manohar Tari','Deshpande, Sunita','nonfiction',213,'Mauj');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Last Mughal, The','Dalrymple, William','history',199,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Social Choice & Welfare, Vol 39 No. 1','Various','economics',235,'Springer');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Radiowaril Bhashane & Shrutika','Deshpande, P L','nonfiction',213,'Mauj');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Gun Gayin Awadi','Deshpande, P L','nonfiction',212,'Mauj');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Aghal Paghal','Deshpande, P L','nonfiction',212,'Mauj');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Maqta-e-Ghalib','Garg, Sanjay','fiction',221,'Mauj');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Beyond Degrees',NULL,'nonfiction',222,'HarperCollins');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Manasa','Kale, V P','nonfiction',213,'Mauj');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'India from Midnight to Milennium','Tharoor, Shashi','history',198,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'World''s Greatest Trials, The',NULL,'history',210,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Great Indian Novel, The','Tharoor, Shashi','fiction',198,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'O Jerusalem!','Lapierre, Dominique','history',217,'vikas');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'City of Joy, The','Lapierre, Dominique','fiction',177,'vikas');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Freedom at Midnight','Lapierre, Dominique','history',167,'vikas');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Winter of Our Discontent, The','Steinbeck, John','fiction',196,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'On Education','Russell, Bertrand','philosophy',203,'Routledge');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Free Will','Harris, Sam','philosophy',203,'FreePress');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Bookless in Baghdad','Tharoor, Shashi','nonfiction',206,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Case of the Lame Canary, The','Gardner, Earle Stanley','fiction',179,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Theory of Everything, The','Hawking, Stephen','science',217,'Jaico');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'New Markets & Other Essays','Drucker, Peter','economics',176,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Electric Universe','Bodanis, David','science',201,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Hunchback of Notre Dame, The','Hugo, Victor','fiction',175,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Burning Bright','Steinbeck, John','fiction',175,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Age of Discontuinity, The','Drucker, Peter','economics',178,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Doctor in the Nude','Gordon, Richard','fiction',179,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Down and Out in Paris & London','Orwell, George','nonfiction',179,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Identity & Violence','Sen, Amartya','philosophy',219,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Beyond the Three Seas','Dalrymple, William','history',197,'Random House');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'World''s Greatest Short Stories, The',NULL,'fiction',217,'Jaico');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Talking Straight','Iacoca, Lee','nonfiction',175,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Maugham''s Collected Short Stories, Vol 3','Maugham, William S','fiction',171,'Vintage');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Phantom of Manhattan, The','Forsyth, Frederick','fiction',180,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Ashenden of The British Agent','Maugham, William S','fiction',160,'Vintage');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Zen & The Art of Motorcycle Maintenance','Pirsig, Robert','philosophy',172,'Vintage');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Great War for Civilization, The','Fisk, Robert','history',197,'HarperCollins');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'We the Living','Rand, Ayn','fiction',178,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Artist and the Mathematician, The','Aczel, Amir','science',186,'HighStakes');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'History of Western Philosophy','Russell, Bertrand','philosophy',213,'Routledge');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Selected Short Stories',NULL,'fiction',215,'Jaico');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Rationality & Freedom','Sen, Amartya','economics',213,'Springer');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Clash of Civilizations and Remaking of the World Order','Huntington, Samuel','history',228,'Simon&Schuster');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Uncommon Wisdom','Capra, Fritjof','nonfiction',197,'Fontana');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'One','Bach, Richard','nonfiction',172,'Dell');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Karl Marx Biography',NULL,'nonfiction',162,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'To Sir With Love','Braithwaite','fiction',197,'Penguin');
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Half A Life','Naipaul, V S','fiction',196,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Discovery of India, The','Nehru, Jawaharlal','history',230,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Apulki','Deshpande, P L','nonfiction',211,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Unpopular Essays','Russell, Bertrand','philosophy',198,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Deceiver, The','Forsyth, Frederick','fiction',178,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Veil: Secret Wars of the CIA','Woodward, Bob','history',171,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Char Shabda','Deshpande, P L','nonfiction',214,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Rosy is My Relative','Durrell, Gerald','fiction',176,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Moon and Sixpence, The','Maugham, William S','fiction',180,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Political Philosophers',NULL,'philosophy',162,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Short History of the World, A','Wells, H G','history',197,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Trembling of a Leaf, The','Maugham, William S','fiction',205,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Doctor on the Brain','Gordon, Richard','fiction',204,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Simpsons & Their Mathematical Secrets','Singh, Simon','science',233,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Pattern Classification','Duda, Hart','data_science',241,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'From Beirut to Jerusalem','Friedman, Thomas','history',202,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Code Book, The','Singh, Simon','science',197,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Age of the Warrior, The','Fisk, Robert','history',197,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Final Crisis',NULL,'comic',257,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Killing Joke, The',NULL,'comic',283,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Flashpoint',NULL,'comic',265,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Batman Earth One',NULL,'comic',265,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Crisis on Infinite Earths',NULL,'comic',258,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Numbers Behind Numb3rs, The','Devlin, Keith','science',202,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Superman Earth One - 1',NULL,'comic',259,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Superman Earth One - 2',NULL,'comic',258,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Justice League: Throne of Atlantis',NULL,'comic',258,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Justice League: The Villain''s Journey',NULL,'comic',258,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Death of Superman, The',NULL,'comic',258,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'History of the DC Universe',NULL,'comic',258,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Batman: The Long Halloween',NULL,'comic',258,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Life in Letters, A','Steinbeck, John','nonfiction',196,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Information, The','Gleick, James','science',233,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Journal of Economics, vol 106 No 3',NULL,'economics',235,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Elements of Information Theory','Thomas, Joy','data_science',229,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Power Electronics - Rashid','Rashid, Muhammad','computer_science',235,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Power Electronics - Mohan','Mohan, Ned','computer_science',237,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Neural Networks','Haykin, Simon','data_science',240,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Grapes of Wrath, The','Steinbeck, John','fiction',196,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Vyakti ani Valli','Deshpande, P L','nonfiction',211,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Statistical Learning Theory','Vapnik, Vladimir','data_science',228,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Empire of the Mughal - The Tainted Throne','Rutherford, Alex','history',180,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Empire of the Mughal - Brothers at War','Rutherford, Alex','history',180,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Empire of the Mughal - Ruler of the World','Rutherford, Alex','history',180,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Empire of the Mughal - The Serpent''s Tooth','Rutherford, Alex','history',180,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Empire of the Mughal - Raiders from the North','Rutherford, Alex','history',180,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Mossad','Baz-Zohar, Michael','history',236,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Jim Corbett Omnibus','Corbett, Jim','nonfiction',223,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'20000 Leagues Under the Sea','Verne, Jules','fiction',190,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Batatyachi Chal','Deshpande P L','fiction',200,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Hafasavnuk','Deshpande P L','fiction',211,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Urlasurla','Deshpande P L','fiction',211,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Pointers in C','Kanetkar, Yashwant','computer_science',213,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Cathedral and the Bazaar, The','Raymond, Eric','computer_science',217,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Design with OpAmps','Franco, Sergio','computer_science',240,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Think Complexity','Downey, Allen','data_science',230,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Devil''s Advocate, The','West, Morris','fiction',178,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Ayn Rand Answers','Rand, Ayn','philosophy',203,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Philosophy: Who Needs It','Rand, Ayn','philosophy',171,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'World''s Great Thinkers, The',NULL,'philosophy',189,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Data Analysis with Open Source Tools','Janert, Phillip','data_science',230,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Broca''s Brain','Sagan, Carl','science',174,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Men of Mathematics','Bell, E T','mathematics',217,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Oxford book of Modern Science Writing','Dawkins, Richard','science',240,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Justice, Judiciary and Democracy','Ranjan, Sudhanshu','philosophy',224,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Arthashastra, The','Kautiyla','philosophy',214,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'We the People','Palkhivala','philosophy',216,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'We the Nation','Palkhivala','philosophy',216,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Courtroom Genius, The','Sorabjee','nonfiction',217,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Dongri to Dubai','Zaidi, Hussain','nonfiction',216,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'History of England, Foundation','Ackroyd, Peter','history',197,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'City of Djinns','Dalrymple, William','history',198,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'India''s Legal System','Nariman','nonfiction',177,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'More Tears to Cry','Sassoon, Jean','fiction',235,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Ropemaker, The','Dickinson, Peter','fiction',196,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Angels & Demons','Brown, Dan','fiction',170,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Judge, The',NULL,'fiction',170,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Attorney, The',NULL,'fiction',170,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Prince, The','Machiavelli','philosophy',173,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Eyeless in Gaza','Huxley, Aldous','fiction',180,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Tales of Beedle the Bard','Rowling, J K','fiction',184,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Girl with the Dragon Tattoo','Larsson, Steig','fiction',179,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Girl who kicked the Hornet''s Nest','Larsson, Steig','fiction',179,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Girl who played with Fire','Larsson, Steig','fiction',179,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Batman Handbook',NULL,'comic',270,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Murphy''s Law',NULL,'nonfiction',178,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Structure and Randomness','Tao, Terence','mathematics',252,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Image Processing with MATLAB','Eddins, Steve','signal_processing',241,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Animal Farm','Orwell, George','fiction',180,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Idiot, The','Dostoevsky, Fyodor','fiction',197,NULL);
INSERT INTO tb_books(id,title,author,genre,height,publisher) VALUES (gen_random_uuid(),'Christmas Carol, A','Dickens, Charles','fiction',196,NULL);